name: "this is my first workflow"

on: 
  push:
    branches:
      - 'features/**'
      - 'main'
      - 'hotfix/**'

jobs:
  Harishvedprakash:
    name: harish singh
    runs-on: gullu-singh
    steps:
    - name: ravi devops
      run: echo harish singh

  

   
 
 
  
